### ISSUE TITLE
Requests For Applications

### ISSUE THREAD

**Issue by burrrata** [temp-nestdao/nest#20]
### ANV DAO
Currently Aragon uses GitHub and Discourse to manage the AGP process. This relies on centralized software and the UX sucks. Aragon needs to lead by example and dogfood its own software (Aragon DAOs) for its own governance process (ANVs). This is so core and critical that I can’t even…

This could be accomplished via a Democracy DAO template and something like the [P2P models Wiki app](https://github.com/P2PModels/wiki).

[Aragon Forum discussion](https://forum.aragon.org/t/aragon-network-vote-dao/1402)

**Comment by burrrata** [comment]
Aragon app that enables subscription services

**Comment by burrrata** [comment]
Pando on mainnet

**Comment by burrrata** [comment]
Liquid democracy (aka delegated voting)

**Comment by burrrata** [comment]
Aragon token curated list app

**Comment by burrrata** [comment]
### Payroll
- The contracts were written. The contracts were audited. The UI was not built and the app was not shipped. Why?

**Comment by burrrata** [comment]
### Aragon Network Explorer
- This would allow us to track daily/weekly/monthly active users in DAOs, ANV participation, DAO template activation, DAO template retention, and other key numbers. This is essential if we want to find product market fit. We need to know what's working and what's not.

**Comment by pythonpete32** [comment]
> ### Liquid democracy (aka delegated voting)
> * Tezos figured it out. If we're rolling our own blockchain, it's the least we could do.

@facuspagnuolo already created the [contracts for this](https://github.com/aragon/aragon-apps/pull/881), we need someone to make a UI for it

**Comment by pythonpete32** [comment]
> ### Token curated list/registry app
> * This would allow DAOs to stack rank any arbitrary data that they want. Could be used for roadmap prioritization, a scoreboard for community prizes, or a recommended book list curated by that DAO's community.

There was a Spec created not long after adchain launched. AFAIK district0x and a few other teams were supposed to all use it. not sure what happened there because district0x launched meme factory a while ago so im assuming they just rolled their own solution. ill reach out Brady and find out what is the situation

**Comment by pythonpete32** [comment]
## Pay Protocol
from the Aragon labs repo

https://github.com/aragonlabs/pay-protocol

**Comment by burrrata** [comment]
### Espresso
- on mainnet

**Comment by burrrata** [comment]
### Aragon Labs
- Everything [here](https://github.com/aragonlabs)!

**Comment by burrrata** [comment]
Moved these into a [Google Doc](https://docs.google.com/document/d/1hKfQYFXRQ8DlsYcnU9yFrSqMpYEqxLivib77FWn61vU/edit?usp=sharing) because this repo and it's Issues will soon be gone.
